[theme]
primaryColor = "#FF9900"
backgroundColor = "#0F141C"
secondaryBackgroundColor = "#18202C"
textColor = "#E5E7EB"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 10
enableWebsocketCompression = true

[browser]
gatherUsageStats = false
